import alchemy from "alchemy"
import { D1Database, DurableObjectNamespace, Worker } from "alchemy/cloudflare"

/**
 * Alchemy Stack for the LiveStore + TanStack DB demo.
 *
 *   - A Cloudflare D1 database for event storage. Migrations are sourced
 *     from `prisma/migrations/`, generated by `prisma migrate diff` against
 *     `prisma/schema.prisma`.
 *   - A Durable Object namespace for the LiveStore `@livestore/sync-cf`
 *     sync backend (named `SYNC_BACKEND_DO` in `wrangler.toml`).
 *   - A single Worker that hosts both:
 *       - The static SPA built by Vite (`./dist/client`).
 *       - The `/sync` WebSocket endpoint that streams events through the
 *         LiveStore sync backend DO, which mirrors them into D1.
 *
 * Run `bun alchemy dev` for hot-reload, `bun alchemy deploy` to push to
 * Cloudflare, `bun alchemy destroy` to tear everything down.
 *
 * NOTE: this stack uses the stable `alchemy@0.93.x` (v1) API. The v2 beta
 * (`alchemy@next`, `2.0.0-beta.x`) is Effect-based but its transitive
 * `@effect/*@0.x` dependency tree still references effect@0.x symbols
 * (`merge`, `tryMap`, `zipRight`, `catchAll`, `CommitPrototype`, `clock`,
 * …) that aren't in the latest published effect@4 betas on npm. The CLI
 * starts but the full deploy can't bundle. Re-test when a unified
 * effect@4 ecosystem ships.
 */
const app = await alchemy("livestore-tanstack-db")

export const db = await D1Database("todos-db", {
  name: "todos-db",
  primaryLocationHint: "wnam",
  migrationsDir: "./prisma/migrations",
  migrationsTable: "d1_migrations",
})

export const syncBackend = await DurableObjectNamespace("sync-backend", {
  className: "SyncBackendDO",
  sqlite: true,
})

export const site = await Worker("site", {
  name: "livestore-tanstack-db-site",
  entrypoint: "./src/cf-worker/index.ts",
  bindings: {
    DB: db,
    SYNC_BACKEND_DO: syncBackend,
  },
  compatibilityDate: "2025-05-08",
  compatibilityFlags: ["enable_request_signal", "nodejs_compat"],
  assets: {
    binding: "ASSETS",
    directory: "./dist/client",
  },
  adopt: true,
})

console.log(`Worker deployed at: ${site.url}`)

await app.finalize()