import alchemy from "alchemy"
import { D1Database, DurableObjectNamespace, Worker } from "alchemy/cloudflare"

/**
 * Alchemy Stack for the LiveStore + TanStack DB demo.
 *
 *   - Cloudflare D1 for event storage. Migrations come from
 *     `prisma/migrations/`, generated by `prisma migrate diff` against
 *     `prisma/schema.prisma`.
 *   - Durable Object namespace for the LiveStore `@livestore/sync-cf` sync
 *     backend (named `SYNC_BACKEND_DO` in `wrangler.toml`).
 *   - A single Worker that hosts both:
 *       - The static SPA built by Vite (`./dist/client`).
 *       - The `/sync` WebSocket endpoint that streams events through the
 *         LiveStore sync backend DO, which mirrors them into D1.
 *
 * Local dev workflow (no Cloudflare login needed):
 *
 *   bun run dev
 *
 * Runs `vite --force` via `@cloudflare/vite-plugin` — Vite serves the
 * SPA, the plugin runs a local worker via wrangler/miniflare that
 * executes `src/cf-worker/index.ts`, and the worker's local DO SQLite
 * holds the in-memory state. No real Cloudflare resources are touched.
 *
 * Cloudflare deploy workflow (requires `bun alchemy login`):
 *
 *   bun run deploy     # plan + apply
 *   bun run destroy    # tear it all down
 *
 * Runs the alchemy CLI which provisions the real D1 + DO + Worker in
 * Cloudflare, applies migrations from `prisma/migrations/`, and ships
 * the bundled SPA from `dist/client/`.
 *
 * NOTE on alchemy v2: we tried `alchemy@next` (2.0.0-beta.x) +
 * `effect@4`. Its transitive `@effect/*@0.x` tree (pulled in by
 * `@livestore/utils`) references effect@0.x runtime APIs (`TRef`,
 * `STM`, `Effect.merge`, `Effect.tryMap`, …) that aren't in any
 * published effect@4 beta on npm. PR #801 advanced it but the
 * migration isn't viable yet. Stay on v1 stable.
 */
const app = await alchemy("livestore-tanstack-db")

export const db = await D1Database("todos-db", {
  name: "todos-db",
  primaryLocationHint: "wnam",
  migrationsDir: "./prisma/migrations",
  migrationsTable: "d1_migrations",
})

export const syncBackend = await DurableObjectNamespace("sync-backend", {
  className: "SyncBackendDO",
  sqlite: true,
})

export const site = await Worker("site", {
  name: "livestore-tanstack-db-site",
  entrypoint: "./src/cf-worker/index.ts",
  bindings: {
    DB: db,
    SYNC_BACKEND_DO: syncBackend,
  },
  compatibilityDate: "2025-05-08",
  compatibilityFlags: ["enable_request_signal", "nodejs_compat"],
  assets: {
    binding: "ASSETS",
    directory: "./dist/client",
  },
  adopt: true,
})

console.log(`Worker deployed at: ${site.url}`)

await app.finalize()