import { Events, makeSchema, Schema, SessionIdSymbol, State } from '@livestore/livestore'

// Generated by `prisma generate` — driven by `prisma/schema.prisma`. This
// is the single source of truth for both the D1 DDL (via `migrations/`)
// and the LiveStore SQLite materialisers below.
import { TodoSchema } from '../../prisma/generated/client-schemas/index.ts'

/**
 * LiveStore SQLite tables.
 *
 * `todos` is a synced table: rows live in both the local store and D1.
 * `uiState` is a client document: it only exists in the local store (one
 * row per session) and is used for ephemeral form state.
 */
export const tables = {
  todos: State.SQLite.table({
    name: 'todos',
    schema: TodoSchema,
  }),
  uiState: State.SQLite.clientDocument({
    name: 'uiState',
    schema: Schema.Struct({
      newTodoText: Schema.String,
      filter: Schema.Union(
        Schema.Literal('all'),
        Schema.Literal('active'),
        Schema.Literal('completed'),
      ),
    }),
    default: { id: SessionIdSymbol, value: { newTodoText: '', filter: 'all' } },
  }),
}

/**
 * LiveStore events. The `v1` prefix is intentional — LiveStore event
 * names are versioned so we can evolve the schema without breaking older
 * clients still replaying the log.
 */
export const events = {
  todoCreated: Events.synced({
    name: 'v1.TodoCreated',
    schema: Schema.Struct({ id: Schema.String, text: Schema.String }),
  }),
  todoCompleted: Events.synced({
    name: 'v1.TodoCompleted',
    schema: Schema.Struct({ id: Schema.String }),
  }),
  todoUncompleted: Events.synced({
    name: 'v1.TodoUncompleted',
    schema: Schema.Struct({ id: Schema.String }),
  }),
  todoDeleted: Events.synced({
    name: 'v1.TodoDeleted',
    schema: Schema.Struct({
      id: Schema.String,
      deletedAt: Schema.Date,
    }),
  }),
  uiStateSet: tables.uiState.set,
} as const

/**
 * Materialisers: how each event mutates the SQLite state. Each
 * `v1.X` event name maps to the corresponding SQL operation.
 *
 * `deletedAt: null` is supplied explicitly on insert because LiveStore's
 * `Schema.NullOr(...)` field is required at write-time (it's the read
 * result that's nullable, not the insert shape).
 */
const materializers = State.SQLite.materializers(events, {
  'v1.TodoCreated': ({ id, text }) =>
    tables.todos.insert({ id, text, completed: false, deletedAt: null }),
  'v1.TodoCompleted': ({ id }) =>
    tables.todos.update({ completed: true }).where({ id }),
  'v1.TodoUncompleted': ({ id }) =>
    tables.todos.update({ completed: false }).where({ id }),
  'v1.TodoDeleted': ({ id, deletedAt }) =>
    tables.todos.update({ deletedAt }).where({ id }),
})

const state = State.SQLite.makeState({ tables, materializers })

export const schema = makeSchema({ events, state })

// Payload sent during the WebSocket handshake. The Cloudflare worker
// validates it before accepting the sync connection.
export const SyncPayload = Schema.Struct({
  authToken: Schema.String,
})