import generatorHelper from "@prisma/generator-helper";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";

const { generatorHandler } = generatorHelper;

/**
 * Prisma generator that emits a LiveStore configuration module from the
 * generated Effect schemas.
 *
 * Run order in `schema.prisma` matters: this generator should come after
 * `prisma-effect-schema-generator` so the Effect schemas it imports already
 * exist.
 *
 * Required config:
 *   - `clientSchemasPath`: path to the file emitted by
 *     `prisma-effect-schema-generator` (e.g. "./generated/client-schemas/index.ts")
 *
 * Emits:
 *   - `liveStoreDbConfig` — the base config passed to `createLiveStoreDb`
 *   - Per-model row types (`TodoRow`, `EventRow`, ...)
 *   - Re-export of `ModelName`
 *
 * Example `schema.prisma`:
 * ```prisma
 * generator livestore {
 *   provider          = "prisma-livestore-generator"
 *   output            = "./generated/livestore"
 *   clientSchemasPath = "./generated/client-schemas/index.ts"
 * }
 * ```
 */
generatorHandler({
  onManifest() {
    return {
      defaultOutput: "prisma/generated/livestore",
      prettyName: "LiveStore",
    };
  },
  async onGenerate(options) {
    const schemaDir = dirname(options.schemaPath);
    const output = options.generator.output?.value ?? "prisma/generated/livestore";
    const clientSchemasPath = options.generator.config.clientSchemasPath;

    if (!clientSchemasPath || typeof clientSchemasPath !== "string") {
      throw new Error(
        "prisma-livestore-generator requires a 'clientSchemasPath' config " +
          "pointing to the generated Effect schemas " +
          '(e.g. "./generated/client-schemas/index.ts")',
      );
    }

    const outputDir = resolve(schemaDir, output);
    const schemasPath = resolve(schemaDir, clientSchemasPath);
    const importPath = relative(outputDir, schemasPath).replace(/\\/g, "/");

    const models = options.dmmf.datamodel.models.map((m) => m.name);

    const schemaImports = models.map((m) => `${m}Schema`).join(", ");
    const rowTypes = models
      .map((m) => `export type ${m}Row = Schema.Schema.Type<typeof ${m}Schema>`)
      .join("\n");
    const modelsObject = models.map((m) => `    ${m}: ${m}Schema`).join(",\n");

    const content = `// AUTO-GENERATED by prisma-livestore-generator -- do not edit.
// Regenerate via \`prisma generate\`.

import type { Schema } from 'effect'
import {
  ${schemaImports},
  PRIMARY_KEY_COLUMNS,
  SOFT_DELETE_COLUMNS,
  TABLES,
  type ModelName,
} from '${importPath}'

${rowTypes}

export const liveStoreDbConfig = {
  models: {
${modelsObject}
  },
  tables: TABLES,
  primaryKeyColumns: PRIMARY_KEY_COLUMNS,
  softDeleteColumns: SOFT_DELETE_COLUMNS,
}

export type { ModelName }
`;

    await mkdir(outputDir, { recursive: true });
    await writeFile(resolve(outputDir, "index.ts"), content);
  },
});
