/**
 * Prisma generator: `prisma/schema.prisma` → `generated/client-schemas/index.ts`
 *
 * The generated file is a plain TypeScript module that re-exports an
 * `Effect` Schema (using `@livestore/utils/effect`'s `Schema` module) for
 * every Prisma model. LiveStore's `State.SQLite.table({ ..., schema: ... })`
 * accepts those schemas directly, so the chain is:
 *
 *   prisma/schema.prisma ──▶ Effect Schema ──▶ LiveStore materialiser
 *
 * This is what keeps `LiveStore` in lock-step with the SQL DDL applied
 * to D1 by Alchemy: change one file, redeploy, both sides move together.
 *
 * The file is `.cjs` because `@prisma/generator-helper@7` ships its
 * public API as CommonJS and Prisma's local-generator support invokes
 * us through Node, not tsx's loader.
 */
const path = require('node:path')
const fs = require('node:fs')
const { generatorHandler } = require('@prisma/generator-helper')

generatorHandler({
  onManifest() {
    return {
      defaultOutput: './generated/client-schemas/index.ts',
      prettyName: 'Effect Schema Generator',
      version: '0.1.0',
    }
  },

  async onGenerate(options) {
    const outputFile =
      options.generator.output?.value ?? './generated/client-schemas/index.ts'
    const outDir = path.dirname(path.resolve(outputFile))
    fs.mkdirSync(outDir, { recursive: true })

    const lines = []
    lines.push(
      '// AUTO-GENERATED by generators/effect-schema.cjs — do not edit.',
      '// Run `bunx prisma generate` to regenerate after editing schema.prisma.',
      '',
      'import { Schema } from "@livestore/utils/effect"',
      '',
    )

    const models = options.dmmf.datamodel.models

    for (const model of models) {
      lines.push(`export const ${model.name}Schema = Schema.Struct({`)
      for (const field of model.fields) {
        if (field.kind !== 'scalar') continue
        const schemaExpr = prismaFieldToEffectSchema(field)
        lines.push(`  ${field.name}: ${schemaExpr},`)
      }
      lines.push('})', '')
    }

    lines.push(
      'export type ModelName =',
      ...models.map((m) => `  | "${m.name}"`),
      '',
      `export const ALL_MODEL_NAMES = ${JSON.stringify(
        models.map((m) => m.name),
      )} as const`,
      '',
    )

    fs.writeFileSync(outputFile, lines.join('\n'))
  },
})

function prismaFieldToEffectSchema(field) {
  let base
  switch (field.type) {
    case 'String':
      base = 'Schema.String'
      break
    case 'Int':
    case 'BigInt':
    case 'Float':
    case 'Decimal':
      base = 'Schema.Number'
      break
    case 'Boolean':
      base = 'Schema.Boolean'
      break
    case 'DateTime':
      base = 'Schema.Date'
      break
    case 'Json':
      base = 'Schema.Unknown'
      break
    case 'Bytes':
      base = 'Schema.Uint8Array'
      break
    default:
      base = 'Schema.String'
  }

  if (field.isList) base = `Schema.Array(${base})`
  if (!field.isRequired) base = `Schema.NullOr(${base})`
  return base
}